### ISSUE TITLE
Time to publish

### ISSUE THREAD

**Issue by khalidzeroual2** [khalidzeroual2/TestRepository-#1]
Hey, @khalido2021  How do we turn on GitHub pages to publish the Game?

**Comment by khalido2021** [comment]
@khalidzeroual2 maybe we should review the project files and ensure we are good to go. and complete the task, please?

**Comment by khalidzeroual2** [comment]
Github Page turned on the game is published  at [gameURL]( https://khalidzeroual2.github.io/TestRepository-/)
